version: '3.8'

services:
  postgres_database:
    image: postgres:latest
    restart: always
    container_name: my_postgres_container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=question_database
    volumes:
      - postgres_data:/var/lib/postgresql_data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=12345
    ports:
      - 5050:80

volumes:
  postgres_data:
