version: '3.8'

services:
  postgres_database:
    image: postgres:latest
    restart: always
    container_name: my_postgres_container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=question_database
    volumes:
      - postgres_data:/var/lib/postgresql_data
  fastapi_app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL = postgresql+asyncpg://postgres:postgres@postgres_database:5432/question_database
    depends_on:
      - postgres_database
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=12345
    ports:
      - 5050:80
    depends_on:
      - postgres_database

volumes:
  postgres_data:
